# ==============================================================================
# Aswin2DEngine - C++ Library CMake Sources
# ==============================================================================

set(PUBLIC_HEADERS
	# --- LOGGER ---
	${ASWIN_ENGINE_INCLUDE_DIR}/LOGGER/CrashLogger.h
	${ASWIN_ENGINE_INCLUDE_DIR}/LOGGER/log.h
	${ASWIN_ENGINE_INCLUDE_DIR}/LOGGER/log.inl
	${ASWIN_ENGINE_INCLUDE_DIR}/LOGGER/LuaLogBinding.h

	# --- WINDOW ---
	${ASWIN_ENGINE_INCLUDE_DIR}/WINDOW/Window.h
	${ASWIN_ENGINE_INCLUDE_DIR}/WINDOW/INPUT/Button.h
	${ASWIN_ENGINE_INCLUDE_DIR}/WINDOW/INPUT/Keyboard.h
	${ASWIN_ENGINE_INCLUDE_DIR}/WINDOW/INPUT/Mouse.h
	${ASWIN_ENGINE_INCLUDE_DIR}/WINDOW/INPUT/MouseButtons.h

	# --- INPUT ---
	${ASWIN_ENGINE_INCLUDE_DIR}/INPUT/KeyListener.h
	${ASWIN_ENGINE_INCLUDE_DIR}/INPUT/MouseListener.h

	# --- RENDERER ---
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/BUFFERS/FrameBuffer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/Batcher.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/BatchRenderer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/Camera2D.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/CircleBatchRenderer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/CoreEngineData.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/FollowCamera.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/LineBatchRenderer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/RectBatchRenderer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/Renderer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/CORE/TextBatchRenderer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/ESSENTIALS/BatchTypes.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/ESSENTIALS/Font.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/ESSENTIALS/FontLoader.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/ESSENTIALS/Primitives.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/ESSENTIALS/Vertex.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/SHADER/Shader.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/SHADER/ShaderLoader.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/TEXTURE/Texture.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/TEXTURE/TextureLoader.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RENDERER/UTILS/OpenGLDebugger.h

	# --- ECS ---
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/ComponentSerializer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/ComponentSerializer.inl
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/Entity.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/Entity.inl
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/MainRegistry.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/MetaUtilities.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/Registry.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/Registry.inl
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/AllComponents.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/AnimationComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/BoxColliderComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/CircleColliderComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/OpenALSoundComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/PhysicsComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/RigidBodyComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/ScriptComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/SoundEmitter.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/SoundListener.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/SpriteComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/TextComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/TileComponent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/ECS/COMPONENTS/TransformComponent.h

	# --- SYSTEMS ---
	${ASWIN_ENGINE_INCLUDE_DIR}/SYSTEMS/AnimationSystem.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SYSTEMS/PhysicsSystem.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SYSTEMS/RenderShapeSystem.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SYSTEMS/RenderSystem.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SYSTEMS/RenderUISystem.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SYSTEMS/ScriptingSystem.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SYSTEMS/SoundSystem.h

	# --- PHYSICS ---
	${ASWIN_ENGINE_INCLUDE_DIR}/PHYSICS/Box2DWrappers.h
	${ASWIN_ENGINE_INCLUDE_DIR}/PHYSICS/ContactListener.h
	${ASWIN_ENGINE_INCLUDE_DIR}/PHYSICS/SensorListener.h
	${ASWIN_ENGINE_INCLUDE_DIR}/PHYSICS/UserData.h

	# --- RESOURCES ---
	${ASWIN_ENGINE_INCLUDE_DIR}/RESOURCES/AssetManager.h
	${ASWIN_ENGINE_INCLUDE_DIR}/RESOURCES/FONTS/default_font.h

	# --- FMOD ---
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_codec.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_common.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_dsp_effects.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_dsp.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_errors.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_output.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_studio_common.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_studio.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod_studio.hpp
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod.h
	${ASWIN_ENGINE_EXTERNAL_LIBS}/FMOD/include/fmod.hpp

	# --- SOUND ---
	${ASWIN_ENGINE_INCLUDE_DIR}/SOUND/AudioEvent.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SOUND/FMODAudioSystem.h

	# --- SOUNDS ---
	${ASWIN_ENGINE_INCLUDE_DIR}/SOUNDS/ESSENTIALS/Music.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SOUNDS/ESSENTIALS/OpenALSound.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SOUNDS/ESSENTIALS/SoundParams.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SOUNDS/MUSICPLAYER/MusicPlayer.h

	# --- OPENALSOUNDS ---
	${ASWIN_ENGINE_INCLUDE_DIR}/OPENALSOUNDS/OpenALDevice.h

	# --- SCRIPTING ---
	${ASWIN_ENGINE_INCLUDE_DIR}/SCRIPTING/ContactListenerBind.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SCRIPTING/GLMLuaBindings.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SCRIPTING/InputManager.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SCRIPTING/RendererBindings.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SCRIPTING/UserDataBinding.h
	${ASWIN_ENGINE_INCLUDE_DIR}/SCRIPTING/UserDataBinding.inl

	# --- STATES ---
	${ASWIN_ENGINE_INCLUDE_DIR}/STATES/State.h
	${ASWIN_ENGINE_INCLUDE_DIR}/STATES/StateMachine.h
	${ASWIN_ENGINE_INCLUDE_DIR}/STATES/StateStack.h
	${ASWIN_ENGINE_INCLUDE_DIR}/STATES/StateSubMachine.h

	# --- UTILITIES ---
	${ASWIN_ENGINE_INCLUDE_DIR}/UTILITIES/2dEngineUtilities.h
	${ASWIN_ENGINE_INCLUDE_DIR}/UTILITIES/RandomGenerator.h
	${ASWIN_ENGINE_INCLUDE_DIR}/UTILITIES/Time.h
	${ASWIN_ENGINE_INCLUDE_DIR}/UTILITIES/Timer.h

	# --- FILESYSTEM ---
	${ASWIN_ENGINE_INCLUDE_DIR}/FILESYSTEM/DIALOGS/FileDialog.h
	${ASWIN_ENGINE_INCLUDE_DIR}/FILESYSTEM/SERIALIZERS/JSONSerializer.h
	${ASWIN_ENGINE_INCLUDE_DIR}/FILESYSTEM/SERIALIZERS/JSONSerializer.inl

	# --- LOADERS ---
	${ASWIN_ENGINE_INCLUDE_DIR}/LOADERS/TilemapLoader.h




)

set(PRIVATE_SOURCES
	# --- stb ---
	${ASWIN_ENGINE_SOURCE_DIR}/STBImplementation.cpp

	# --- LOGGER ---
	${ASWIN_ENGINE_SOURCE_DIR}/LOGGER/CrashLogger.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/LOGGER/log.cpp

	# --- WINDOW ---
	${ASWIN_ENGINE_SOURCE_DIR}/WINDOW/Window.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/WINDOW/INPUT/Mouse.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/WINDOW/INPUT/Keyboard.cpp

	# --- INPUT ---
	${ASWIN_ENGINE_SOURCE_DIR}/INPUT/KeyListener.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/INPUT/MouseListener.cpp

	# --- RENDERER ---
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/BUFFERS/FrameBuffer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/Batcher.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/BatchRenderer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/Camera2D.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/CircleBatchRenderer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/CoreEngineData.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/FollowCamera.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/LineBatchRenderer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/RectBatchRenderer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/Renderer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/CORE/TextBatchRenderer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/ESSENTIALS/Font.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/ESSENTIALS/FontLoader.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/SHADER/Shader.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/TEXTURE/Texture.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/RENDERER/UTILS/OpenGLDebugger.cpp

	# --- ECS ---
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/ComponentSerializer.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/Entity.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/MainRegistry.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/MetaUtilities.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/Registry.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/AnimationComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/BoxColliderComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/CircleColliderComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/OpenALSoundComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/PhysicsComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/RigidBodyComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/SoundEmitter.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/SoundListener.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/SpriteComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/TextComponent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/ECS/COMPONENTS/TransformComponent.cpp

	# --- SYSTEMS ---
	${ASWIN_ENGINE_SOURCE_DIR}/SYSTEMS/AnimationSystem.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SYSTEMS/PhysicsSystem.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SYSTEMS/RenderShapeSystem.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SYSTEMS/RenderSystem.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SYSTEMS/RenderUISystem.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SYSTEMS/ScriptingSystem.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SYSTEMS/SoundSystem.cpp

	# --- PHYSICS ---
	${ASWIN_ENGINE_SOURCE_DIR}/PHYSICS/Box2DWrappers.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/PHYSICS/ContactListener.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/PHYSICS/SensorListener.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/PHYSICS/UserData.cpp

	# --- RESOURCES ---
	${ASWIN_ENGINE_SOURCE_DIR}/RESOURCES/AssetManager.cpp

	# --- SOUND ---
	${ASWIN_ENGINE_SOURCE_DIR}/SOUND/AudioEvent.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SOUND/FMODAudioSystem.cpp

	# --- SOUNDS ---
	${ASWIN_ENGINE_SOURCE_DIR}/SOUNDS/ESSENTIALS/OpenALSound.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SOUNDS/ESSENTIALS/miniaudio_implementation.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SOUNDS/ESSENTIALS/Music.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SOUNDS/MUSICPLAYER/MusicPlayer.cpp

	# --- OPENALSOUNDS ---
	${ASWIN_ENGINE_SOURCE_DIR}/OPENALSOUNDS/OpenALDevice.cpp

	# --- SCRIPTING ---
	${ASWIN_ENGINE_SOURCE_DIR}/SCRIPTING/ContactListenerBind.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SCRIPTING/GLMLuaBindings.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SCRIPTING/InputManager.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SCRIPTING/RendererBindings.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SCRIPTING/SensorListenerBind.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/SCRIPTING/UserDataBinding.cpp

	# --- STATES ---
	${ASWIN_ENGINE_SOURCE_DIR}/STATES/State.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/STATES/StateMachine.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/STATES/StateStack.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/STATES/StateSubMachine.cpp

	# --- UTILITIES ---
	${ASWIN_ENGINE_SOURCE_DIR}/UTILITIES/RandomGenerator.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/UTILITIES/Time.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/UTILITIES/Timer.cpp

		# --- FILESYSTEM ---
	${ASWIN_ENGINE_SOURCE_DIR}/FILESYSTEM/DIALOGS/FileDialog.cpp
	${ASWIN_ENGINE_SOURCE_DIR}/FILESYSTEM/SERIALIZERS/JSONSerializer.cpp

		# --- LOADERS ---
	${ASWIN_ENGINE_SOURCE_DIR}/LOADERS/TilemapLoader.cpp
)
